/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/1.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0, -333.65]}>
        <mesh
          geometry={nodes.Mesh_Frame.geometry}
          material={nodes.Mesh_Frame.material}
          position={[0, -92.45, -14.11]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          geometry={nodes.Mesh_Frame_top.geometry}
          material={nodes.Mesh_Frame_top.material}
          position={[0, 159.37, -228.16]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1.5, -1.5, 1.5]}
        />
        <mesh
          geometry={nodes.Side_details.geometry}
          material={nodes.Side_details.material}
          position={[0, -92.45, 135.89]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[1, 0.5, 1]}
        />
        <mesh
          geometry={nodes.Clips.geometry}
          material={nodes.Clips.material}
          position={[0, -92.45, 135.89]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[1, 0.5, 1]}
        />
        <mesh
          geometry={nodes.Middle_pipes.geometry}
          material={nodes.Middle_pipes.material}
          position={[0, -92.45, 135.89]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[1, 0.5, 1]}
        />
        <mesh
          geometry={nodes.Bottom_chambers.geometry}
          material={nodes.Bottom_chambers.material}
          position={[0, -84.34, 135.89]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[1, 0.5, 1]}
        />
        <mesh
          geometry={nodes.Bottom_pipes.geometry}
          material={nodes.Bottom_pipes.material}
          position={[0, -92.45, 135.89]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[1, 0.5, 1]}
        />
        <mesh
          geometry={nodes.Bottom_side_holders.geometry}
          material={nodes.Bottom_side_holders.material}
          position={[0, -92.45, 135.89]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[1, 0.5, 1]}
        />
      </group>
      <group position={[0, -92.45, -337.75]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Metaverse.geometry}
          material={nodes.Metaverse.material}
          position={[0, 40.5, -92.45]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        <mesh geometry={nodes.Mesh.geometry} material={nodes.Mesh.material} position={[0, -10, 0]} />
        <mesh
          geometry={nodes.Mesh_top.geometry}
          material={nodes.Mesh_top.material}
          position={[0, -224.05, -251.82]}
          rotation={[-Math.PI, 0, 0]}
          scale={[1.5, -1.5, 1.5]}
        />
        <mesh
          geometry={nodes.Mesh_bolts_top.geometry}
          material={nodes.Mesh_bolts_top.material}
          position={[0, -224.05, -251.82]}
          rotation={[-Math.PI, 0, 0]}
          scale={[1.5, -1.5, 1.5]}
        />
        <mesh geometry={nodes.Mesh_bolts.geometry} material={nodes.Mesh_bolts.material} position={[0, -10, 0]} />
        <mesh
          geometry={nodes.Side_chambers_right.geometry}
          material={nodes.Side_chambers_right.material}
          position={[0, -10, 0]}
        />
        <mesh
          geometry={nodes.Left_body.geometry}
          material={nodes.Left_body.material}
          position={[0, 140, 0]}
          scale={[1, 0.5, 1]}
        />
        <mesh
          geometry={nodes.Right_body.geometry}
          material={nodes.Right_body.material}
          position={[0, 140, 0]}
          scale={[1, 0.5, 1]}
        />
      </group>
      <group position={[0, 0, -137.55]} rotation={[-Math.PI, 0, -Math.PI]}>
        <mesh geometry={nodes.Serial_Number_1.geometry} material={nodes.Serial_Number_1.material} />
      </group>
      <mesh geometry={nodes.Back.geometry} material={nodes.Back.material} />
      <group position={[0, 0, -7.13]}>
        <mesh geometry={nodes.Glass_back.geometry} material={nodes.Glass_back.material} position={[0, 0, 7.13]} />
        <mesh geometry={nodes.Glass_Front.geometry} material={nodes.Glass_Front.material} position={[0, 0, -7.13]} />
      </group>
      <group position={[19.66, -4.04, -35.05]} rotation={[0, -0.01, 0]} scale={[27.56, 27.56, 27.56]}>
        <mesh
          geometry={nodes.Dial_minute.geometry}
          material={nodes.Dial_minute.material}
          position={[-0.73, 0.5, 0.46]}
          rotation={[Math.PI / 2, 0.81, 0]}
          scale={[1, 1, 1.5]}
        />
        <mesh
          geometry={nodes.Dial_second.geometry}
          material={nodes.Dial_second.material}
          position={[-0.74, 0.49, 0.64]}
          rotation={[-Math.PI / 2, 1.52, -Math.PI]}
          scale={[0.11, 0.01, 0.54]}
        />
        <mesh
          geometry={nodes.Dial_hour.geometry}
          material={nodes.Dial_hour.material}
          position={[-0.74, 0.49, 0.35]}
          rotation={[Math.PI / 2, -0.78, 0]}
          scale={[1, 1, 1.5]}
        />
      </group>
      <group position={[0, 104.25, -65.26]}>
        <mesh
          geometry={nodes.Path_11_1.geometry}
          material={nodes.Path_11_1.material}
          position={[0, 115.67, 52.98]}
          scale={[1.5, 1.5, 1]}>
          <mesh geometry={nodes.Rounding_1_4.geometry} material={nodes.Rounding_1_4.material}>
            <mesh geometry={nodes.Cap_1_6.geometry} material={nodes.Cap_1_6.material} />
          </mesh>
          <mesh geometry={nodes.Rounding_2_4.geometry} material={nodes.Rounding_2_4.material}>
            <mesh geometry={nodes.Cap_2_6.geometry} material={nodes.Cap_2_6.material} />
          </mesh>
        </mesh>
      </group>
      <group position={[0, -87.98, -17.07]}>
        <group position={[7.03, 93.61, 0.36]}>
          <mesh geometry={nodes['1'].geometry} material={nodes['1'].material} position={[-25.26, 160.54, 0]}>
            <mesh geometry={nodes.Rounding_1_14.geometry} material={nodes.Rounding_1_14.material}>
              <mesh geometry={nodes.Cap_1_16.geometry} material={nodes.Cap_1_16.material} />
            </mesh>
            <mesh geometry={nodes.Rounding_2_14.geometry} material={nodes.Rounding_2_14.material}>
              <mesh geometry={nodes.Cap_2_16.geometry} material={nodes.Cap_2_16.material} />
            </mesh>
          </mesh>
          <mesh geometry={nodes['2'].geometry} material={nodes['2'].material} position={[1.71, 160.54, 0]}>
            <mesh geometry={nodes.Rounding_1_15.geometry} material={nodes.Rounding_1_15.material}>
              <mesh geometry={nodes.Cap_1_17.geometry} material={nodes.Cap_1_17.material} />
            </mesh>
            <mesh geometry={nodes.Rounding_2_15.geometry} material={nodes.Rounding_2_15.material}>
              <mesh geometry={nodes.Cap_2_17.geometry} material={nodes.Cap_2_17.material} />
            </mesh>
          </mesh>
          <mesh geometry={nodes['3'].geometry} material={nodes['3'].material} position={[137.11, 0, 0]}>
            <mesh geometry={nodes.Rounding_1_16.geometry} material={nodes.Rounding_1_16.material}>
              <mesh geometry={nodes.Cap_1_18.geometry} material={nodes.Cap_1_18.material} />
            </mesh>
            <mesh geometry={nodes.Rounding_2_16.geometry} material={nodes.Rounding_2_16.material}>
              <mesh geometry={nodes.Cap_2_18.geometry} material={nodes.Cap_2_18.material} />
            </mesh>
          </mesh>
          <mesh geometry={nodes['6'].geometry} material={nodes['6'].material} position={[-11.23, -159.13, 0]}>
            <mesh geometry={nodes.Rounding_1_17.geometry} material={nodes.Rounding_1_17.material}>
              <mesh geometry={nodes.Cap_1_19.geometry} material={nodes.Cap_1_19.material} />
            </mesh>
            <mesh geometry={nodes.Rounding_2_17.geometry} material={nodes.Rounding_2_17.material}>
              <mesh geometry={nodes.Cap_2_19.geometry} material={nodes.Cap_2_19.material} />
            </mesh>
          </mesh>
          <mesh geometry={nodes['9'].geometry} material={nodes['9'].material} position={[-150.47, 0, 0]}>
            <mesh geometry={nodes.Rounding_1_18.geometry} material={nodes.Rounding_1_18.material}>
              <mesh geometry={nodes.Cap_1_20.geometry} material={nodes.Cap_1_20.material} />
            </mesh>
            <mesh geometry={nodes.Rounding_2_18.geometry} material={nodes.Rounding_2_18.material}>
              <mesh geometry={nodes.Cap_2_20.geometry} material={nodes.Cap_2_20.material} />
            </mesh>
          </mesh>
        </group>
      </group>
      <group position={[71.94, 104.25, -65.26]}>
        <mesh geometry={nodes.Path_311_1.geometry} material={nodes.Path_311_1.material}>
          <mesh geometry={nodes.Rounding_1_5.geometry} material={nodes.Rounding_1_5.material}>
            <mesh geometry={nodes.Cap_1_7.geometry} material={nodes.Cap_1_7.material} />
          </mesh>
          <mesh geometry={nodes.Rounding_2_5.geometry} material={nodes.Rounding_2_5.material}>
            <mesh geometry={nodes.Cap_2_7.geometry} material={nodes.Cap_2_7.material} />
          </mesh>
        </mesh>
        <mesh geometry={nodes.Path_331.geometry} material={nodes.Path_331.material}>
          <mesh geometry={nodes.Rounding_1_6.geometry} material={nodes.Rounding_1_6.material}>
            <mesh geometry={nodes.Cap_1_8.geometry} material={nodes.Cap_1_8.material} />
          </mesh>
          <mesh geometry={nodes.Rounding_2_6.geometry} material={nodes.Rounding_2_6.material}>
            <mesh geometry={nodes.Cap_2_8.geometry} material={nodes.Cap_2_8.material} />
          </mesh>
        </mesh>
        <mesh geometry={nodes.wa_logo_mark_011.geometry} material={nodes.wa_logo_mark_011.material}>
          <mesh geometry={nodes.Rounding_1_7.geometry} material={nodes.Rounding_1_7.material}>
            <mesh geometry={nodes.Cap_1_9.geometry} material={nodes.Cap_1_9.material} />
          </mesh>
          <mesh geometry={nodes.Rounding_2_7.geometry} material={nodes.Rounding_2_7.material}>
            <mesh geometry={nodes.Cap_2_9.geometry} material={nodes.Cap_2_9.material} />
          </mesh>
        </mesh>
        <mesh geometry={nodes.Path_71.geometry} material={nodes.Path_71.material}>
          <mesh geometry={nodes.Rounding_1_8.geometry} material={nodes.Rounding_1_8.material}>
            <mesh geometry={nodes.Cap_1_10.geometry} material={nodes.Cap_1_10.material} />
          </mesh>
          <mesh geometry={nodes.Rounding_2_8.geometry} material={nodes.Rounding_2_8.material}>
            <mesh geometry={nodes.Cap_2_10.geometry} material={nodes.Cap_2_10.material} />
          </mesh>
        </mesh>
        <mesh geometry={nodes.numbers_1.geometry} material={nodes.numbers_1.material} position={[8.15, 11.53, 0]}>
          <mesh geometry={nodes.Rounding_1_9.geometry} material={nodes.Rounding_1_9.material}>
            <mesh geometry={nodes.Cap_1_11.geometry} material={nodes.Cap_1_11.material} />
          </mesh>
          <mesh geometry={nodes.Rounding_2_9.geometry} material={nodes.Rounding_2_9.material}>
            <mesh geometry={nodes.Cap_2_11.geometry} material={nodes.Cap_2_11.material} />
          </mesh>
        </mesh>
      </group>
      <group position={[231, 4.96, -75.45]}>
        <mesh
          geometry={nodes.W_Crown.geometry}
          material={nodes.W_Crown.material}
          position={[10.78, 0.2, 0.27]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[3.3, 6.6, 3.3]}
        />
        <mesh
          geometry={nodes.Crown_1.geometry}
          material={nodes.Crown_1.material}
          position={[-18.28, -0.2, -0.27]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
          scale={0.16}
        />
      </group>
      <group position={[0.45, 6.86, 2.84]}>
        <mesh geometry={nodes.BOLT1.geometry} material={nodes.BOLT1.material} position={[-172.53, 178.74, 0]} />
        <mesh geometry={nodes.BOLT2.geometry} material={nodes.BOLT2.material} position={[172.74, 178.74, 0]} />
        <mesh geometry={nodes.BOLT3.geometry} material={nodes.BOLT3.material} position={[-203.43, 0.83, 0]} />
        <mesh geometry={nodes.BOLT4.geometry} material={nodes.BOLT4.material} position={[203.02, 0.83, 0]} />
        <mesh geometry={nodes.BOLT5.geometry} material={nodes.BOLT5.material} position={[-172.53, -179.57, 0]} />
        <mesh geometry={nodes.BOLT6.geometry} material={nodes.BOLT6.material} position={[172.74, -179.57, 0]} />
      </group>
      <group position={[0.66, 5.84, -66.07]}>
        <mesh geometry={nodes.Spring3.geometry} material={nodes.Spring3.material} position={[-186.46, 1.7, 1.38]} />
        <mesh geometry={nodes.Spring4.geometry} material={nodes.Spring4.material} position={[186.46, 1.7, -6.9]} />
        <mesh geometry={nodes.Spring2.geometry} material={nodes.Spring2.material} position={[162.77, 179.07, 1.38]} />
        <mesh geometry={nodes.Spring6.geometry} material={nodes.Spring6.material} position={[160.88, -180.84, 1.38]} />
        <mesh geometry={nodes.Spring5.geometry} material={nodes.Spring5.material} position={[-163.49, -180.84, 1.38]} />
        <mesh geometry={nodes.Spring1.geometry} material={nodes.Spring1.material} position={[-164.76, 179.07, 1.38]} />
      </group>
      <group position={[-65, 8.7, 0]}>
        <mesh
          geometry={nodes.Extrude_NURBS.geometry}
          material={nodes.Extrude_NURBS.material}
          position={[0, -209.11, -46.64]}
          rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Cap_1.geometry}
            material={nodes.Cap_1.material}
            position={[0, 11.3, 1.23]}
            scale={1.5}
          />
          <mesh
            geometry={nodes.Cap_2.geometry}
            material={nodes.Cap_2.material}
            position={[0, 11.3, 1.23]}
            scale={1.5}
          />
        </mesh>
      </group>
      <mesh
        geometry={nodes.Front_inner_ridge.geometry}
        material={nodes.Front_inner_ridge.material}
        position={[0, 0, -15.67]}
      />
      <mesh
        geometry={nodes.Back_inner_ridge.geometry}
        material={nodes.Back_inner_ridge.material}
        position={[0, 0, -136.44]}
      />
      <group position={[0, 0, -34.16]}>
        <group position={[0, 0, 34.16]}>
          <mesh
            geometry={nodes.Extrude.geometry}
            material={nodes.Extrude.material}
            position={[204, 0, -74.62]}
            rotation={[1.57, 1.55, -1.57]}
            scale={[2, 8, 1]}
          />
        </group>
        <group position={[0, 0, 34.16]}>
          <mesh
            geometry={nodes.Extrude_1.geometry}
            material={nodes.Extrude_1.material}
            position={[-199, 0, -74.62]}
            rotation={[-1.57, 1.55, 1.57]}
            scale={[2, 8, 1]}
          />
        </group>
        <mesh geometry={nodes.frame.geometry} material={nodes.frame.material} />
      </group>
      <group position={[0.66, 5.84, -60.59]}>
        <mesh geometry={nodes.Tube3.geometry} material={nodes.Tube3.material} position={[-186.46, 1.7, 1.38]} />
        <mesh geometry={nodes.Tube4.geometry} material={nodes.Tube4.material} position={[186.46, 1.7, -6.9]} />
        <mesh geometry={nodes.Tube2.geometry} material={nodes.Tube2.material} position={[162.77, 179.22, 1.38]} />
        <mesh geometry={nodes.Tube6.geometry} material={nodes.Tube6.material} position={[160.88, -180.84, 1.38]} />
        <mesh geometry={nodes.Tube5.geometry} material={nodes.Tube5.material} position={[-163.49, -180.84, 1.38]} />
        <mesh geometry={nodes.Tube1.geometry} material={nodes.Tube1.material} position={[-164.76, 179.07, 1.38]} />
      </group>
      <mesh
        geometry={nodes.Ceiling_inside.geometry}
        material={nodes.Ceiling_inside.material}
        position={[0, 236.13, -76.44]}
      />
      <mesh
        geometry={nodes.Floor_inside.geometry}
        material={nodes.Floor_inside.material}
        position={[0, -202.38, -76.44]}
      />
      <mesh geometry={nodes.Frame_fromt.geometry} material={nodes.Frame_fromt.material} position={[0, 0, -15.67]}>
        <mesh geometry={nodes.Rounding_1.geometry} material={nodes.Rounding_1.material}>
          <mesh geometry={nodes.Cap_1_2.geometry} material={nodes.Cap_1_2.material} />
        </mesh>
        <mesh geometry={nodes.Rounding_2.geometry} material={nodes.Rounding_2.material}>
          <mesh geometry={nodes.Cap_2_2.geometry} material={nodes.Cap_2_2.material} />
        </mesh>
      </mesh>
      <mesh
        geometry={nodes.Front_screw_shell.geometry}
        material={nodes.Front_screw_shell.material}
        position={[0, 0, -16.58]}>
        <mesh
          geometry={nodes.Rounding_1_1.geometry}
          material={nodes.Rounding_1_1.material}
          position={[0, -0.24, 11.28]}>
          <mesh geometry={nodes.Cap_1_3.geometry} material={nodes.Cap_1_3.material} />
        </mesh>
        <mesh
          geometry={nodes.Rounding_2_1.geometry}
          material={nodes.Rounding_2_1.material}
          position={[0, -0.24, 11.28]}>
          <mesh geometry={nodes.Cap_2_3.geometry} material={nodes.Cap_2_3.material} />
        </mesh>
      </mesh>
      <mesh geometry={nodes.Frame_back.geometry} material={nodes.Frame_back.material} position={[0, 0, -117.3]}>
        <mesh geometry={nodes.Rounding_1_2.geometry} material={nodes.Rounding_1_2.material}>
          <mesh geometry={nodes.Cap_1_4.geometry} material={nodes.Cap_1_4.material} />
        </mesh>
        <mesh geometry={nodes.Rounding_2_2.geometry} material={nodes.Rounding_2_2.material}>
          <mesh geometry={nodes.Cap_2_4.geometry} material={nodes.Cap_2_4.material} />
        </mesh>
      </mesh>
      <mesh
        geometry={nodes.Screw_shell_back.geometry}
        material={nodes.Screw_shell_back.material}
        position={[0, 0, -136.85]}>
        <mesh
          geometry={nodes.Rounding_1_3.geometry}
          material={nodes.Rounding_1_3.material}
          position={[0, -0.24, 11.28]}>
          <mesh geometry={nodes.Cap_1_5.geometry} material={nodes.Cap_1_5.material} />
        </mesh>
        <mesh
          geometry={nodes.Rounding_2_3.geometry}
          material={nodes.Rounding_2_3.material}
          position={[0, -0.24, 11.28]}>
          <mesh geometry={nodes.Cap_2_5.geometry} material={nodes.Cap_2_5.material} />
        </mesh>
      </mesh>
      <mesh
        geometry={nodes.Roman_disc.geometry}
        material={nodes.Roman_disc.material}
        position={[71.94, 104.25, -67.16]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <group position={[0, 8.01, -112.6]} scale={[1.19, 1.19, 1.19]}>
        <mesh
          geometry={nodes.Pivot.geometry}
          material={nodes.Pivot.material}
          position={[-0.34, 8.34, -25.16]}
          scale={[0.84, 0.84, 0.84]}
        />
        <mesh
          geometry={nodes.Cog_Front1.geometry}
          material={nodes.Cog_Front1.material}
          position={[-44.43, 79.11, -463.91]}
          rotation={[0, 0, 1.43]}
          scale={[1.25, 1.25, 5.01]}
        />
        <mesh
          geometry={nodes.Cog_center_back.geometry}
          material={nodes.Cog_center_back.material}
          position={[1.56, 2.72, -103.33]}
          rotation={[0, 0, 1.56]}
        />
        <mesh
          geometry={nodes.Cog_left_back.geometry}
          material={nodes.Cog_left_back.material}
          position={[-85.39, 37.53, -83.14]}
          rotation={[0, 0, -1.7]}
          scale={[0.63, 0.63, 1]}
        />
        <mesh
          geometry={nodes.Circle40.geometry}
          material={nodes.Circle40.material}
          position={[82.46, -115.01, -38]}
          rotation={[0, 0, -0.13]}
          scale={[0.43, 0.43, 0.54]}
        />
        <mesh
          geometry={nodes.Circle25.geometry}
          material={nodes.Circle25.material}
          position={[66.57, 33.96, -8.55]}
          scale={1.15}
        />
        <mesh
          geometry={nodes.Circle22.geometry}
          material={nodes.Circle22.material}
          position={[46.99, -109.91, 11.45]}
        />
        <mesh
          geometry={nodes.Object04.geometry}
          material={nodes.Object04.material}
          position={[16.58, -138.96, -66.95]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={1.31}
        />
        <mesh
          geometry={nodes.Shape23.geometry}
          material={nodes.Shape23.material}
          position={[66.57, 33.96, -70.76]}
          scale={1.15}
        />
        <mesh
          geometry={nodes.Circle26.geometry}
          material={nodes.Circle26.material}
          position={[114.14, -81.01, -16.06]}
        />
        <mesh
          geometry={nodes.Circle28.geometry}
          material={nodes.Circle28.material}
          position={[114.16, -80.82, -39.59]}
          rotation={[0, 0, -0.13]}
          scale={[0.46, 0.46, 0.54]}
        />
        <mesh
          geometry={nodes.Circle29.geometry}
          material={nodes.Circle29.material}
          position={[114.16, -80.82, -43.42]}
          rotation={[0, 0, -0.05]}
          scale={[0.46, 0.46, 0.54]}
        />
        <mesh
          geometry={nodes.Circle35.geometry}
          material={nodes.Circle35.material}
          position={[46.99, -109.91, -17.87]}
        />
        <mesh
          geometry={nodes.Circle38.geometry}
          material={nodes.Circle38.material}
          position={[46.95, -109.77, -43.16]}
          rotation={[0, 0, -0.13]}
          scale={[0.43, 0.43, 0.54]}
        />
        <mesh
          geometry={nodes.Circle41.geometry}
          material={nodes.Circle41.material}
          position={[82.46, -115.01, -43.19]}
          rotation={[0, 0, -0.05]}
          scale={[0.43, 0.43, 0.54]}
        />
        <mesh
          geometry={nodes.Circle42.geometry}
          material={nodes.Circle42.material}
          position={[17.59, 52.88, -8.22]}
          rotation={[0, 0, 1.4]}
          scale={1.21}
        />
        <mesh
          geometry={nodes.Circle43.geometry}
          material={nodes.Circle43.material}
          position={[84.59, 8.81, -8.22]}
          rotation={[0, 0, 1.4]}
          scale={1.06}
        />
        <mesh geometry={nodes.Object07.geometry} material={nodes.Object07.material} position={[59.06, 3.03, -97.71]} />
        <mesh geometry={nodes.Object08.geometry} material={nodes.Object08.material} position={[1.56, 2.72, -94.95]} />
        <mesh
          geometry={nodes.Shape27.geometry}
          material={nodes.Shape27.material}
          position={[9.81, -105.94, -106.26]}
          scale={[0.35, 0.35, 1]}
        />
        <mesh
          geometry={nodes.Object09.geometry}
          material={nodes.Object09.material}
          position={[62.71, -72.27, -70.87]}
          rotation={[0, 0, -0.05]}
          scale={[0.66, 0.66, 1]}
        />
        <mesh
          geometry={nodes.Circle45.geometry}
          material={nodes.Circle45.material}
          position={[62.71, -72.27, -47.66]}
          rotation={[0, 0, -0.05]}
          scale={[0.6, 0.6, 0.66]}
        />
        <mesh
          geometry={nodes.Object10.geometry}
          material={nodes.Object10.material}
          position={[121.04, -27.33, -66.37]}
          rotation={[0, 0, -0.05]}
          scale={[0.84, 0.84, 0.83]}
        />
        <mesh
          geometry={nodes.Circle47.geometry}
          material={nodes.Circle47.material}
          position={[73.58, -33.11, -55.39]}
          rotation={[0, 0, -0.05]}
          scale={[0.43, 0.43, 0.69]}
        />
        <mesh
          geometry={nodes.Object11.geometry}
          material={nodes.Object11.material}
          position={[73.58, -33.11, -79.47]}
          rotation={[0, 0, 1.71]}
          scale={[0.47, 0.47, 1.04]}
        />
        <mesh
          geometry={nodes.Shape28.geometry}
          material={nodes.Shape28.material}
          position={[1.56, 2.72, -98.5]}
          rotation={[0, 0, Math.PI / 6]}
        />
        <mesh
          geometry={nodes.Shape31.geometry}
          material={nodes.Shape31.material}
          position={[-54.39, -69.21, -100.38]}
          rotation={[0, 0, -0.97]}
        />
        <mesh
          geometry={nodes.Object24.geometry}
          material={nodes.Object24.material}
          position={[-54.39, -69.21, -97.71]}
          scale={[3.67, 3.67, 1]}
        />
        <mesh
          geometry={nodes.Circle56.geometry}
          material={nodes.Circle56.material}
          position={[-65.03, -32.26, -93.09]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[1.71, 1.71, 1.71]}
        />
        <group position={[-19.37, -94.51, -10.95]}>
          <mesh
            geometry={nodes.Circle33.geometry}
            material={nodes.Circle33.material}
            position={[10.65, 37.59, 8.73]}
            scale={[1.21, 1.21, 1.21]}
          />
          <mesh
            geometry={nodes.Circle32.geometry}
            material={nodes.Circle32.material}
            position={[20.99, -7.77, 8.73]}
            scale={[1.06, 1.06, 1.06]}
          />
          <mesh
            geometry={nodes.Circle31.geometry}
            material={nodes.Circle31.material}
            position={[-21.12, -36.05, 8.73]}
            scale={[1.06, 1.06, 1.06]}
          />
          <mesh
            geometry={nodes.Circle34.geometry}
            material={nodes.Circle34.material}
            position={[0.53, -13.91, -89.85]}
            rotation={[0, 0, -0.17]}
            scale={2.02}
          />
          <mesh geometry={nodes.Line14.geometry} material={nodes.Line14.material} position={[3.64, 0.55, -8.46]} />
        </group>
        <group position={[-54.39, -69.21, 7.16]}>
          <mesh
            geometry={nodes.Circle53.geometry}
            material={nodes.Circle53.material}
            position={[0, 0, -2.41]}
            scale={0.81}
          />
          <mesh geometry={nodes.Circle52.geometry} material={nodes.Circle52.material} position={[0, 0, -1.85]} />
          <mesh
            geometry={nodes.Object19.geometry}
            material={nodes.Object19.material}
            position={[0, 0, -0.68]}
            scale={[0.52, 0.52, 0.52]}
          />
          <mesh geometry={nodes.Shape37.geometry} material={nodes.Shape37.material} position={[0, 0, -0.8]} />
          <mesh
            geometry={nodes.Object20.geometry}
            material={nodes.Object20.material}
            position={[0, 0, -0.68]}
            scale={[0.52, 0.52, 0.52]}
          />
          <mesh
            geometry={nodes.Shape38.geometry}
            material={nodes.Shape38.material}
            position={[0, 0, -0.68]}
            scale={[0.52, 0.52, 0.52]}
          />
          <mesh
            geometry={nodes.Object21.geometry}
            material={nodes.Object21.material}
            position={[0, 0, -0.68]}
            scale={[0.52, 0.52, 0.52]}
          />
          <mesh
            geometry={nodes.Object22.geometry}
            material={nodes.Object22.material}
            position={[0, 0, -0.68]}
            scale={[0.52, 0.52, 0.52]}
          />
          <mesh geometry={nodes.Object23.geometry} material={nodes.Object23.material} position={[0, 0, -1.85]} />
          <mesh geometry={nodes.Line22.geometry} material={nodes.Line22.material} position={[0.86, 0.49, -0.84]} />
          <mesh
            geometry={nodes.Shape39.geometry}
            material={nodes.Shape39.material}
            position={[-13.64, -10.27, -0.86]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[0.1, 0.1, 0.1]}
          />
        </group>
        <group position={[-63.47, -77.84, 1.14]}>
          <mesh geometry={nodes.Circle54.geometry} material={nodes.Circle54.material} position={[9.07, 8.58, 1.93]} />
          <mesh
            geometry={nodes.Circle55.geometry}
            material={nodes.Circle55.material}
            position={[9.07, 8.58, 0.57]}
            rotation={[0, 0, -Math.PI / 2]}
          />
          <mesh geometry={nodes.Shape40.geometry} material={nodes.Shape40.material} position={[9.07, 8.58, 3.03]} />
          <mesh
            geometry={nodes.Shape41.geometry}
            material={nodes.Shape41.material}
            position={[-18.49, 52.09, 0.4]}
            scale={[0.41, 0.41, 1]}
          />
        </group>
        <group position={[-39.81, -29.46, -10.81]}>
          <mesh
            geometry={nodes.Shape36.geometry}
            material={nodes.Shape36.material}
            position={[-33.72, 10.02, -1.19]}
            scale={[0.1, 0.1, 0.1]}
          />
          <mesh geometry={nodes.Line24.geometry} material={nodes.Line24.material} position={[-52.6, 18.39, -0.52]} />
          <mesh geometry={nodes.Line21.geometry} material={nodes.Line21.material} position={[64.24, -25.75, -0.52]} />
          <mesh geometry={nodes.Line23.geometry} material={nodes.Line23.material} position={[-69.79, -63.33, -0.52]} />
        </group>
        <group position={[20.01, 43.06, -3.71]} rotation={[0, 0, -2.52]}>
          <group position={[55.14, -100.57, -7.3]} rotation={[0, 0, -0.91]}>
            <mesh geometry={nodes.Line030.geometry} material={nodes.Line030.material} position={[3.64, 0.55, -8.46]} />
            <mesh
              geometry={nodes.Circle058.geometry}
              material={nodes.Circle058.material}
              position={[10.65, 37.59, 8.73]}
              scale={1.21}
            />
            <mesh
              geometry={nodes.Circle059.geometry}
              material={nodes.Circle059.material}
              position={[20.99, -7.77, 8.73]}
              scale={1.06}
            />
            <mesh
              geometry={nodes.Circle060.geometry}
              material={nodes.Circle060.material}
              position={[-21.12, -36.05, 8.73]}
              scale={1.06}
            />
            <mesh
              geometry={nodes.Circle061.geometry}
              material={nodes.Circle061.material}
              position={[0.53, -13.91, -89.85]}
              rotation={[0, 0, -0.17]}
              scale={[2.02, 2.02, 2.02]}
            />
          </group>
          <group position={[6.42, -0.03, -7.37]}>
            <mesh
              geometry={nodes.Line033.geometry}
              material={nodes.Line033.material}
              position={[-69.79, -63.33, -0.52]}
            />
            <mesh
              geometry={nodes.Line034.geometry}
              material={nodes.Line034.material}
              position={[64.24, -25.75, -0.52]}
            />
            <mesh
              geometry={nodes.Shape060.geometry}
              material={nodes.Shape060.material}
              position={[-33.72, 10.02, -1.19]}
              scale={0.1}
            />
          </group>
          <group position={[15.73, -73.32, -7.52]} rotation={[0, 0, 2.59]}>
            <mesh
              geometry={nodes.Circle066.geometry}
              material={nodes.Circle066.material}
              position={[20.99, -7.77, 8.73]}
              scale={[1.06, 1.06, 1.06]}
            />
            <mesh geometry={nodes.Line035.geometry} material={nodes.Line035.material} position={[3.64, 0.55, -8.46]} />
            <mesh
              geometry={nodes.Circle067.geometry}
              material={nodes.Circle067.material}
              position={[0.53, -13.91, -89.85]}
              rotation={[0, 0, -0.17]}
              scale={2.02}
            />
            <mesh
              geometry={nodes.Circle068.geometry}
              material={nodes.Circle068.material}
              position={[10.65, 37.59, 8.73]}
              scale={[1.21, 1.21, 1.21]}
            />
            <mesh
              geometry={nodes.Circle069.geometry}
              material={nodes.Circle069.material}
              position={[-21.12, -36.05, 8.73]}
              scale={[1.06, 1.06, 1.06]}
            />
          </group>
          <mesh
            geometry={nodes.Shape051.geometry}
            material={nodes.Shape051.material}
            position={[-88.72, -44.38, -22.01]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[0.21, 0.21, 1.05]}
          />
          <mesh
            geometry={nodes.Circle064.geometry}
            material={nodes.Circle064.material}
            position={[-18.8, -2.82, -89.65]}
            rotation={[0, 0, Math.PI / 2]}
            scale={[1.71, 1.71, 1.71]}
          />
          <mesh geometry={nodes.Line031.geometry} material={nodes.Line031.material} position={[-61.96, 1.52, -7.89]} />
        </group>
        <group position={[-134.15, -14.14, 3.4]} rotation={[0, 0, -2.19]} scale={[0.8, 0.8, 0.8]}>
          <mesh geometry={nodes.Line036.geometry} material={nodes.Line036.material} position={[3.64, 0.55, -8.46]} />
          <mesh
            geometry={nodes.Circle070.geometry}
            material={nodes.Circle070.material}
            position={[10.65, 37.59, 8.73]}
            scale={[1.21, 1.21, 1.21]}
          />
          <mesh
            geometry={nodes.Circle071.geometry}
            material={nodes.Circle071.material}
            position={[20.99, -7.77, 8.73]}
            scale={[1.06, 1.06, 1.06]}
          />
          <mesh
            geometry={nodes.Circle072.geometry}
            material={nodes.Circle072.material}
            position={[-21.12, -36.05, 8.73]}
            scale={[1.06, 1.06, 1.06]}
          />
          <mesh
            geometry={nodes.Circle073.geometry}
            material={nodes.Circle073.material}
            position={[0.53, -13.91, -89.85]}
            rotation={[0, 0, -0.17]}
            scale={[2.02, 2.02, 2.02]}
          />
        </group>
        <mesh
          geometry={nodes.Shape062.geometry}
          material={nodes.Shape062.material}
          position={[59.98, 80.83, -130.82]}
          rotation={[0, 0, 1.09]}
          scale={[1.48, 1.48, 2.06]}
        />
        <mesh
          geometry={nodes.Shape046.geometry}
          material={nodes.Shape046.material}
          position={[133.81, -11.53, -69.46]}
          rotation={[0, 0, 1.58]}
          scale={[1.71, 1.71, 1.71]}
        />
        <mesh geometry={nodes.Circle04.geometry} material={nodes.Circle04.material} position={[7.38, 139.79, -16.06]} />
        <mesh
          geometry={nodes.Rectangle02.geometry}
          material={nodes.Rectangle02.material}
          position={[86.11, 115.32, -16.06]}
          rotation={[0, 0, -0.65]}
        />
        <mesh geometry={nodes.Line01.geometry} material={nodes.Line01.material} position={[26.27, -120.74, -28.31]} />
        <mesh geometry={nodes.Line04.geometry} material={nodes.Line04.material} position={[130.09, -71.37, 5.23]} />
        <mesh geometry={nodes.Shape10.geometry} material={nodes.Shape10.material} position={[46.99, -109.91, -37.48]} />
        <mesh
          geometry={nodes.Line05.geometry}
          material={nodes.Line05.material}
          position={[-143.19, -50.54, 4.1]}
          rotation={[0, 0, 0.06]}
        />
        <mesh
          geometry={nodes.Object01.geometry}
          material={nodes.Object01.material}
          position={[-44.43, 79.11, -56.62]}
          rotation={[0, 0, -2.04]}
        />
        <mesh
          geometry={nodes.Object.geometry}
          material={nodes.Object.material}
          position={[60.04, 80.63, -314.19]}
          rotation={[0, 0, 1.08]}
          scale={[1.09, 1.09, 4.85]}
        />
        <mesh
          geometry={nodes.Circle13.geometry}
          material={nodes.Circle13.material}
          position={[-25.25, -101.28, -72.51]}
          rotation={[0, 0, 1.32]}
          scale={[1.64, 1.64, 1.64]}
        />
        <mesh geometry={nodes.Shape11.geometry} material={nodes.Shape11.material} position={[130.09, -71.37, -6.54]} />
        <mesh
          geometry={nodes.Circle15.geometry}
          material={nodes.Circle15.material}
          position={[84.94, -117.22, -62.49]}
          rotation={[0, 0, -0.41]}
          scale={[1.37, 1.37, 1.37]}
        />
        <mesh geometry={nodes.Arc03.geometry} material={nodes.Arc03.material} position={[-50.18, 62.04, -16.06]} />
        <mesh geometry={nodes.Shape20.geometry} material={nodes.Shape20.material} position={[0.47, 0.07, -50.45]} />
        <mesh geometry={nodes.Circle20.geometry} material={nodes.Circle20.material} position={[6.38, 141.97, 10.61]} />
        <mesh geometry={nodes.Shape18.geometry} material={nodes.Shape18.material} position={[1.03, 0.23, -71.04]} />
        <mesh
          geometry={nodes.Shape22.geometry}
          material={nodes.Shape22.material}
          position={[16.58, -138.96, -64.18]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={1.31}
        />
        <mesh
          geometry={nodes.Object06.geometry}
          material={nodes.Object06.material}
          position={[66.57, 33.96, -73.21]}
          scale={1.15}
        />
        <mesh geometry={nodes.Line12.geometry} material={nodes.Line12.material} position={[68.62, -93.09, -16.06]} />
        <mesh geometry={nodes.Line13.geometry} material={nodes.Line13.material} position={[-135.83, 26.65, -8.23]} />
        <mesh
          geometry={nodes.Line17.geometry}
          material={nodes.Line17.material}
          position={[52.84, 39.54, -25.41]}
          rotation={[0, 0, 1.4]}
        />
        <mesh
          geometry={nodes.Line18.geometry}
          material={nodes.Line18.material}
          position={[-146.96, -43.87, 0.93]}
          rotation={[0, 0, -0.04]}
        />
        <mesh geometry={nodes.Line19.geometry} material={nodes.Line19.material} position={[16.32, -73.3, -10.58]} />
        <mesh
          geometry={nodes.Line20.geometry}
          material={nodes.Line20.material}
          position={[-135.42, -34.7, -16.07]}
          rotation={[0, 0, 0.06]}
        />
        <mesh
          geometry={nodes.Object12.geometry}
          material={nodes.Object12.material}
          position={[-5, 124.47, -4.32]}
          rotation={[0, 0, 2.01]}
          scale={[0.95, 0.95, 1.05]}
        />
        <mesh
          geometry={nodes.Object18.geometry}
          material={nodes.Object18.material}
          position={[31.77, -125.28, -28.31]}
        />
        <mesh geometry={nodes.Line25.geometry} material={nodes.Line25.material} position={[-108.19, -27.92, -11.34]} />
        <mesh
          geometry={nodes.Object25.geometry}
          material={nodes.Object25.material}
          position={[-54.39, -69.21, -97.71]}
          scale={[4.86, 4.86, 1]}
        />
        <mesh
          geometry={nodes.Circle57.geometry}
          material={nodes.Circle57.material}
          position={[-106.44, -62.89, -11.34]}
        />
        <mesh geometry={nodes.Shape01.geometry} material={nodes.Shape01.material} position={[0.47, 0.07, -19.58]} />
        <mesh
          geometry={nodes.Line037.geometry}
          material={nodes.Line037.material}
          position={[41, 71.79, -28.29]}
          rotation={[0, 0, 2.46]}
        />
        <mesh
          geometry={nodes.Cog_center.geometry}
          material={nodes.Cog_center.material}
          position={[-0.44, 1.72, -263.33]}
          rotation={[0, 0, 2.89]}
          scale={[0.51, 0.51, 3]}
        />
        <mesh
          geometry={nodes.Cog_front2.geometry}
          material={nodes.Cog_front2.material}
          position={[60.04, 80.63, -377.17]}
          rotation={[0, 0, -2.09]}
          scale={[0.83, 0.83, 4.13]}
        />
        <mesh
          geometry={nodes.Cog_right.geometry}
          material={nodes.Cog_right.material}
          position={[59.06, 3.03, -105.14]}
          rotation={[0, 0, 1.17]}
        />
        <mesh
          geometry={nodes.Cog_back.geometry}
          material={nodes.Cog_back.material}
          position={[-54.39, -69.21, -106.27]}
          rotation={[0, 0, 1.7]}
          scale={[0.81, 0.81, 1]}
        />
        <mesh
          geometry={nodes.Screws_left.geometry}
          material={nodes.Screws_left.material}
          position={[-134.95, -73.82, -25.45]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.21, 0.21, 1.05]}
        />
        <mesh
          geometry={nodes.Circle08.geometry}
          material={nodes.Circle08.material}
          position={[37.28, -58.77, -37.48]}
        />
        <mesh
          geometry={nodes.Circle09.geometry}
          material={nodes.Circle09.material}
          position={[-136.67, -41.79, -42.7]}
          rotation={[0, 0, 0.06]}
        />
        <mesh geometry={nodes.Circle14.geometry} material={nodes.Circle14.material} position={[-37.5, -125.53, 7.99]} />
        <mesh
          geometry={nodes.Circle16.geometry}
          material={nodes.Circle16.material}
          position={[114.86, 59.01, 11.96]}
          scale={[1.76, 1.76, 1.76]}
        />
        <mesh
          geometry={nodes.Circle17.geometry}
          material={nodes.Circle17.material}
          position={[66.81, 138.88, 13.09]}
          scale={[1.06, 1.06, 1.06]}
        />
        <mesh
          geometry={nodes.Shape12.geometry}
          material={nodes.Shape12.material}
          position={[-127.22, 28.05, -4.32]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={1.05}
        />
        <mesh
          geometry={nodes.Circle18.geometry}
          material={nodes.Circle18.material}
          position={[43.84, 137.47, -69.72]}
          scale={1.7}
        />
        <mesh
          geometry={nodes.Circle19.geometry}
          material={nodes.Circle19.material}
          position={[133.73, -12.09, -69.64]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[1.71, 1.71, 1.71]}
        />
        <mesh geometry={nodes.Shape13.geometry} material={nodes.Shape13.material} position={[-129.08, 2.89, -3.03]} />
        <mesh
          geometry={nodes.Shape17.geometry}
          material={nodes.Shape17.material}
          position={[-5, 124.47, -4.32]}
          rotation={[0, 0, 2.01]}
          scale={[0.95, 0.95, 1.05]}
        />
        <mesh
          geometry={nodes.Circle21.geometry}
          material={nodes.Circle21.material}
          position={[-0.59, -69.82, -41.31]}
          scale={[0.54, 0.54, 1]}
        />
        <mesh geometry={nodes.Shape21.geometry} material={nodes.Shape21.material} position={[46.99, -109.91, -42.43]} />
        <mesh
          geometry={nodes.Object02.geometry}
          material={nodes.Object02.material}
          position={[46.99, -109.91, -44.55]}
        />
        <mesh
          geometry={nodes.Object03.geometry}
          material={nodes.Object03.material}
          position={[46.99, -109.91, 11.45]}
        />
        <mesh
          geometry={nodes.Circle23.geometry}
          material={nodes.Circle23.material}
          position={[16.58, -138.96, 6.38]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={1.31}
        />
        <mesh
          geometry={nodes.Object05.geometry}
          material={nodes.Object05.material}
          position={[16.58, -138.96, 6.38]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={1.31}
        />
        <mesh
          geometry={nodes.Circle27.geometry}
          material={nodes.Circle27.material}
          position={[114.16, -80.82, -35.96]}
          rotation={[0, 0, 0.92]}
          scale={[0.46, 0.46, 0.54]}
        />
        <mesh
          geometry={nodes.Circle30.geometry}
          material={nodes.Circle30.material}
          position={[114.16, -80.82, -47.05]}
          rotation={[0, 0, -0.13]}
          scale={[0.46, 0.46, 0.54]}
        />
        <mesh
          geometry={nodes.Circle37.geometry}
          material={nodes.Circle37.material}
          position={[46.95, -109.77, -38.17]}
          rotation={[0, 0, -0.05]}
          scale={[0.43, 0.43, 0.54]}
        />
        <mesh
          geometry={nodes.Circle44.geometry}
          material={nodes.Circle44.material}
          position={[64.05, 55.19, -8.09]}
          rotation={[0, 0, 1.4]}
          scale={1.06}
        />
        <mesh geometry={nodes.Shape26.geometry} material={nodes.Shape26.material} position={[-1.23, -2.16, -27.17]} />
        <mesh
          geometry={nodes.Circle46.geometry}
          material={nodes.Circle46.material}
          position={[121.04, -27.33, -47.11]}
          rotation={[0, 0, 0.89]}
          scale={[0.77, 0.77, 0.55]}
        />
        <mesh
          geometry={nodes.Shape32.geometry}
          material={nodes.Shape32.material}
          position={[-73.89, 80.31, -274.75]}
          rotation={[0, 0, 0.88]}
          scale={[1, 1, 3]}
        />
      </group>
      <group position={[9, -515, -459]}>
        <group position={[-7.06, 501.65, -27.81]} rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.leather_link.geometry}
            material={nodes.leather_link.material}
            position={[0, -466.35, 14.35]}
          />
        </group>
      </group>
      <mesh
        geometry={nodes.Engine_Body.geometry}
        material={nodes.Engine_Body.material}
        position={[0, -92.45, -349.22]}
      />
    </group>
  )
}

useGLTF.preload('/1.gltf')
