/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/test.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <PerspectiveCamera
        makeDefault={false}
        far={2000000}
        near={0.01}
        fov={50}
        position={[-13.83, 4.81, 6.17]}
        rotation={[-0.43, -1.09, -0.39]}
      />
      <mesh geometry={nodes.Plane.geometry} material={materials.SHadowCatcher3} scale={2.68} />
      <mesh geometry={nodes['Mesh_(2)'].geometry} material={materials['Metal 201']} />
    </group>
  )
}

useGLTF.preload('/test.glb')
